services:
  backend:
    image: trainrex/cardboardbound-backend
    build: ./backend
    restart: unless-stopped
    user: "${MY_UID}:${MY_GID}"
  frontend:
    image: trainrex/cardboardbound-frontend
    build: ./frontend
    restart: unless-stopped
    user: "${MY_UID}:${MY_GID}"
  webserver:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
