services:
  backend:
    image: ghcr.io/tannerstephens/cardboardbound-backend:latest
    restart: unless-stopped
  frontend:
    image: ghcr.io/tannerstephens/cardboardbound-frontend:latest
    restart: unless-stopped
  webserver:
    image: nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    restart: unless-stopped
