services:
  backend:
    image: trainrex/cardboardbound-backend
    build: ./backend
    command: "python dev.py"
    environment:
      - DATABASE_URI=sqlite:///database.db
    volumes:
      - ./backend:/home/appuser
    restart: unless-stopped
    user: "${MY_UID}:${MY_GID}"
  frontend:
    image: node
    volumes:
      - ./frontend/frontend:/app
    working_dir: /app
    command: bash -c "yarn install && npm run dev -- --host 0.0.0.0 --port 80"
    restart: unless-stopped
    user: "${MY_UID}:${MY_GID}"
  webserver:
    image: nginx
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
