services:
  backend:
    image: trainrex/cardboardbound-backend
    build: ./backend
    restart: unless-stopped
  frontend:
    image: trainrex/cardboardbound-frontend
    build: ./frontend
    restart: unless-stopped
  webserver:
    image: nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
