services:
  backend:
    image: trainrex/cardboardbound-backend
    build: ./backend
    ports:
      - "5000:5000"
    command: "python dev.py"
    volumes:
      - ./backend:/home/appuser
    restart: unless-stopped
