version: 3

tasks:
  build:
    cmds:
      - docker compose -f docker-compose.dev.yml build
  up:
    cmds:
      - docker compose -f docker-compose.dev.yml up -d
  down:
    cmds:
      - docker compose -f docker-compose.dev.yml down
  make-migrations:
    cmds:
      - docker compose -f docker-compose.dev.yml run --rm backend alembic revision --autogenerate
  migrate:
    cmds:
      - docker compose -f docker-compose.dev.yml run --rm backend alembic upgrade head
